version: '3'
services:
  outbox:
    build: .
    links: 
      - af-connect-redis
    ports:
      - "8100:8100"
    depends_on:
      - af-connect-redis
  af-connect-redis:
    container_name: "redis-db"
    image: "redis:alpine"