version: '3'
services:
  outbox:
    build: .
    link: 
      - redis
    ports:
      - "8100:8100"
    networks:
      - redis
  redis:
    image: "redis:alpine"
    ports:
      - target: 6379
    networks:
      - redis
networks:
  redis:
    driver: bridge
